"""
Dictionary values of DSPs and their subSources for mapping
"""

DSPS = {
    "Apple / iTunes": ["Apple", "iTunes"],
    "Spotify": ["Spotify"],
    "Tencent [QQ, Kuwo, Kugou]": ["Tencent", "QQ Music", "Kuwo", "Kugou"],
    "Amazon": ["Amazon"],
    "Tidal": ["Tidal", "Aspiro"],
    "Jiosaavn": ["Jiosaavn", "Saavn", "Jio"],
    "Facebook / Instagram": ["Facebook", "Meta", "Instagram", "Whatsapp"],
    "Youtube / Google": ["Youtube", "Google"],
    "Qobuz": ["Qobuz"],
    "Deezer": ["Deezer"],
    "Anghami": ["Anghami"],
    "Audiomack": ["Audiomack"],
    "Napster": ["Napster"],
    "Netease": ["Netease"],
    "Boomplay": ["Boomplay"],
    "Pandora": ["Pandora"],
    "Soundcloud": ["Soundcloud"],
    "Bandcamp": ["Bandcamp"],
    "Peloton": ["Peloton"],
    "Beatport": ["Beatport"],
    "Juno": ["Juno"],
    "Traxsource": ["Traxsource"],
    "Imusica": ["Imusica"],
    "Resso": ["Resso"],
    "Mixcloud": ["Mixcloud"],
    "Twitch": ["Twitch"],
    "Audoo": ["Audoo"],
    "7Digital": ["7Digital"],
    "Sirius XM": ["Sirius XM"],
    "Vevo": ["Vevo"],
    "Touchtunes": ["Touchtunes"],
    "Genie": ["Genie"],
    "Joox": ["Joox"],
    "KK Box": ["KK Box"],
    "Beatsource": ["Beatsource"],
    "Moov": ["Moov"],
    "Chandos": ["Chandos"],
    "eMusic": ["eMusic"],
    "HDTracks": ["HDTracks"],
    "Yoto": ["Yoto"],
    "Twitter": ["Twitter"],
    "TikTok": ["TikTok"],
    "Yousician": ["Yousician"],
    "Melody VR": ["Melody VR"],
    "Chordify": ["Chordify"],
    "Canal+": ["Canal"],
    "Snap": ["Snap"],
    "Daily Motion": ["Daily Motion"],
    "iHeart": ["iHeart"],
    "Lucky Voice": ["Lucky Voice"],
    "Ultimate Guitar": ["Ultimate Guitar"],
    "Viacom": ["Viacom"],
    "Lyric Find": ["Lyric Find"],
    "Music Notes": ["Music Notes"],
    "Musixmatch": ["Musixmatch"],
}
